### ISSUE TITLE
Project Submission

### ISSUE THREAD

**Issue by SyntaxColoring** [codingisbliss/Compiler#4]
On Piazza, the professor asked us to describe what we have so far. Here's what I've written up:

Max Marrone and Madhur Biyani

NOT DONE

Description:

- We're using Python.  Everything up to the code generation is hand-written.  Code generation uses llvmlite to output formatted and validated LLVM IR.
- The scanner works.
- The parser works.
- Code generation and semantic analysis are limited to:
  - Printing.
  - Global declarations of tuples.
  - Assignment statements.
- Error recovery doesn't work. The compiler stops on the first error.

What we hope to do:

- We want to implement as much functionality as we can in the global scope.
- We can probably have arithmetic and exchange assignments done by the end of tomorrow (Sunday).
- We can probably have some control flow done by Tuesday?

Does that seem reasonable?

I have a final on Monday, other projects due Tuesday, and graduation ceremonies on Wednesday and Thursday.  So I'm not going to be very useful.  But if you want to work on the code, I can explain things.

**Comment by codingisbliss** [comment]
Sounds good to me, I will look at the code and ask if I need some explanation for it,

**Comment by SyntaxColoring** [comment]
Note submitted through Piazza.  I don't think there's a way to share it with you, so if they reply, I'll copy their reply here.

**Comment by SyntaxColoring** [comment]
Professor's response:

> [There is a way to make it visible to both of you, but I am not sure you can create such a thing.  I could not figure out a way to change it's visibility.  Life's too short. :-) ]
> 
>  
> 
> Received.  Could you please update us as to your progress (as it's past Sunday by now).
> 
>  
> 
> Also can you clarify: what's with the semantic/type checking: can it handle functions at all?  tuple assignements and friends?
> 
> 
> 
> No pressure: Have plenty of exams to grade (have an exam tonight), but let me know how things are going...
> 

My reply:
> 
> The following has been done over the weekend:
> * In the global scope:
>   * The complete set of tuple operations - declarations, assignments, exchanges
>   * Arithmetic
>   * If-statements (including elsif, nesting, etc.)
>   * While-loops
>   * Statement-level semantic error recovery - if one statement is semantically invalid, we still check the ones that come after it
>  
> 
> Semantic analysis and type checking happens as part of the code generation.  What we can generate code for (as described above) is what we type check, and vice-versa.  What is implemented, is implemented correctly - no tuple use before declaration, no duplicate declaration, etc.
> 
>  
> 
> Functions are not supported at all.

**Comment by SyntaxColoring** [comment]
> Understood.  Are you planning to continue or to stop at this.  I am not sure when the cut off is.  Tomorrow is still OK, but not sure how much past that.
>  
> 
> Also, to be clear: the stuff you do not have code generation for you also do not have semantic checking for: so no function etc at all?
> 
>  
> 
> No pressure---you can stop any time you like, as long as what you hand in [compiles and] runs on the advertised set of features.  We will figure out the grading scheme.  Somehow.

> > Also, to be clear: the stuff you do not have code generation for you also do not have semantic checking for: so no function etc at all?
>
> Correct.
> 
> > Are you planning to continue or to stop at this
>
> We'd like to implement arrays, at least, so that we can demo some less trivial programs.
